name: Daily SMS Reminders

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9 AM UTC every day
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Check Required Secrets
        run: |
          if [ -z "${{ secrets.VERCEL_URL }}" ]; then
            echo "Error: VERCEL_URL secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.CRON_SECRET_KEY }}" ]; then
            echo "Error: CRON_SECRET_KEY secret is not set"
            exit 1
          fi
          echo "Required secrets are set"
          echo "Using Vercel URL: ${{ secrets.VERCEL_URL }}"

      - name: Send HTTP Request
        run: |
          # Make sure URL starts with https://
          VERCEL_URL="${{ secrets.VERCEL_URL }}"
          if [[ ! $VERCEL_URL =~ ^https:// ]]; then
            VERCEL_URL="https://${VERCEL_URL}"
          fi
          
          echo "Making request to: ${VERCEL_URL}/api/cron/reminders"
          echo "Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          
          # First make a verbose request to see headers
          echo "Testing endpoint with verbose output..."
          curl -X GET "${VERCEL_URL}/api/cron/reminders" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" \
            -H "Content-Type: application/json" \
            -v \
            -L \
            2>&1 | sed 's/Bearer [^ ]*/Bearer ***/'
          
          echo "\n--- Making actual request ---\n"
          
          response=$(curl -X GET "${VERCEL_URL}/api/cron/reminders" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" \
            -H "Content-Type: application/json" \
            -w "\n%{http_code}\n%{url_effective}\n%{time_total}\n%{size_download}\n%{speed_download}" \
            -L \
            -s)
          
          # Extract the response components
          speed_download=$(echo "$response" | tail -n1)
          size_download=$(echo "$response" | tail -n2 | head -n1)
          time_total=$(echo "$response" | tail -n3 | head -n1)
          url_effective=$(echo "$response" | tail -n4 | head -n1)
          status_code=$(echo "$response" | tail -n5 | head -n1)
          body=$(echo "$response" | sed 'N;$!N;$!N;$!N;$d')
          
          echo "Response body: $body"
          echo "Status code: $status_code"
          echo "Final URL: $url_effective"
          echo "Request time: ${time_total}s"
          echo "Response size: ${size_download} bytes"
          echo "Download speed: ${speed_download} bytes/sec"
          
          if [ "$status_code" -ge 400 ]; then
            echo "Error: Request failed with status $status_code"
            echo "Full response: $response"
            exit 1
          fi
          
          echo "Reminder check completed successfully"
