name: Daily SMS Reminders

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9 AM UTC every day
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Check Vercel URL
        run: |
          if [ -z "${{ secrets.VERCEL_URL }}" ]; then
            echo "Error: VERCEL_URL secret is not set"
            exit 1
          fi
          echo "Using Vercel URL: ${{ secrets.VERCEL_URL }}"

      - name: Send HTTP Request
        run: |
          # Make sure URL starts with https://
          VERCEL_URL="${{ secrets.VERCEL_URL }}"
          if [[ ! $VERCEL_URL =~ ^https:// ]]; then
            VERCEL_URL="https://${VERCEL_URL}"
          fi
          echo "Making request to: ${VERCEL_URL}/api/cron/reminders"
          
          response=$(curl -X GET "${VERCEL_URL}/api/cron/reminders" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" \
            -H "Content-Type: application/json" \
            -w "\n%{http_code}\n%{url_effective}" \
            -L \
            -s)
          
          # Extract the last two lines (status code and final URL)
          url_effective=$(echo "$response" | tail -n1)
          status_code=$(echo "$response" | tail -n2 | head -n1)
          body=$(echo "$response" | sed 'N;$d')
          
          echo "Response body: $body"
          echo "Status code: $status_code"
          echo "Final URL: $url_effective"
          
          if [ "$status_code" -ge 400 ]; then
            echo "Error: Request failed with status $status_code"
            exit 1
          fi
